In [1]:
import numpy as np

In [2]:
data = np.genfromtxt(".\\cars2.csv",delimiter=',',dtype=None,names=True,encoding='utf-8')

In [3]:
data.dtype.names


('Car', 'Model', 'Volume', 'Weight', 'CO2')

In [4]:
data['Car'].size

36

In [5]:
data['Car']

array(['Toyoty', 'Mitsubishi', 'Skoda', 'Fiat', 'Mini', 'VW', 'Skoda',
       'Mercedes', 'Ford', 'Audi', 'Hyundai', 'Suzuki', 'Ford', 'Honda',
       'Hundai', 'Opel', 'BMW', 'Mazda', 'Skoda', 'Ford', 'Ford', 'Opel',
       'Mercedes', 'Skoda', 'Volvo', 'Mercedes', 'Audi', 'Audi', 'Volvo',
       'BMW', 'Mercedes', 'Volvo', 'Ford', 'BMW', 'Opel', 'Mercedes'],
      dtype='<U10')

In [6]:
#Mostrar los modelos de la marca "Mercedes"
coches = data['Car']
mercedes = np.where(coches=='Mercedes')
modelos = data['Model']
modelos[mercedes]

array(['A-Class', 'C-Class', 'CLA', 'E-Class', 'SLK'], dtype='<U10')

In [7]:
volumen = data['Volume']
#volumen de los coches mercedes
print(volumen[mercedes])
mod = modelos[mercedes]
#Modelos de coches de la marca Mercedes dónde el volumen es >= 2.1
mod[np.where(volumen[mercedes]>=2.1)]


[1.5 2.1 1.5 2.1 2.5]


array(['C-Class', 'E-Class', 'SLK'], dtype='<U10')

In [8]:
#Modelos de coches de la marca Mercedes dónde el volumen es >= 2.1 y su peso sea < 1500

vol = np.where(volumen[mercedes]>=2.1)
print("Modelos de Mercedes con volumen >=2.1\n")
print(mod[vol])
mod_vol = mod[vol]

peso = data['Weight']
peso_mercedes = peso[mercedes]
peso_mercedes_vol = peso_mercedes[vol]
print("Pesos de coches Mercedes con volumen >=2.1\n")
print(peso_mercedes_vol)

peso_mod_vol = np.where(peso_mercedes_vol<1500)
print("Índices de los pesos menores de 1500 en modelos Mercedes con volumen >=2.1")
print(peso_mod_vol)
mod_vol[peso_mod_vol]





Modelos de Mercedes con volumen >=2.1

['C-Class' 'E-Class' 'SLK']
Pesos de coches Mercedes con volumen >=2.1

[1365 1605 1395]
Índices de los pesos menores de 1500 en modelos Mercedes con volumen >=2.1
(array([0, 2], dtype=int64),)


array(['C-Class', 'SLK'], dtype='<U10')

In [16]:
ford = np.where(coches=='Ford')
mod_ford = modelos[ford]
print(mod_ford)

co2 = data['CO2']
co2_ford = co2[ford]
min_co2_ford = np.min(co2_ford)
print(min_co2_ford)

min_co2 = np.min(co2)
print(f"CO2 Maximo {max_co2}")
max_co2 = np.max(co2)
print(f"CO2 Minimo {min_co2}")

min_marca = coches[co2 == min_co2]
max_marca = coches[co2 == max_co2]
print(f"Marcas con el CO2 Minimo {min_marca}")
print(f"Marcas con el CO2 Maximo {max_marca}")

['Fiesta' 'Fiesta' 'Focus' 'Mondeo' 'B-Max']
94
CO2 Maximo 120
CO2 Minimo 90
Marcas con el CO2 Minimo ['Fiat' 'Skoda']
Marcas con el CO2 Maximo ['Mercedes']
