In [1]:
lista = [1,2,3,4]
print(lista)

[1, 2, 3, 4]


In [4]:
import numpy as np
print(np.array(lista))
np.array(lista)

[1 2 3 4]


array([1, 2, 3, 4])

In [12]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
d = np.zeros((2,3), dtype = int)
print(d)

[[0 0 0]
 [0 0 0]]


In [25]:
o = np.ones((2,3), dtype = int)
print(o)

[[1 1 1]
 [1 1 1]]


In [29]:
g = range(3,8,2)
for i in g:
    print(i)

3
5
7


In [30]:
y = np.arange(2,20,2)
print(y)
for i in y:
    print(i)

[ 2  4  6  8 10 12 14 16 18]
2
4
6
8
10
12
14
16
18


In [37]:
a = np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])