In [11]:
import numpy as np
array = np.arange(5)
print(array)
print(array[array%2 == 0])

y = np.array([10,20,30,15,50])

print(y)

print(y+array)

z = np.where(y > 30)

print(z)

print(f"Los numeros mayores que 30 del array y son: {y[z]}")

aMult = np.multiply(array,y)

print(aMult)

[0 1 2 3 4]
[0 2 4]
[10 20 30 15 50]
[10 21 32 18 54]
(array([4], dtype=int64),)
Los numeros mayores que 30 del array y son: [50]
[  0  20  60  45 200]
